# Generated by Django 3.0.7 on 2020-09-10 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accdetails', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='creditcard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_card', models.CharField(choices=[('1', 'State Bank of India'), ('2', 'Central Bank of India'), ('3', 'Swiss Bank '), ('4', 'Bank of Baroda'), ('5', 'HDFC'), ('6', 'Credit one'), ('7', 'ICICI')], max_length=1)),
                ('CardNo', models.BigIntegerField()),
                ('Firstname', models.CharField(max_length=50)),
                ('Lastname', models.CharField(max_length=50)),
                ('CVV', models.IntegerField()),
                ('Purpose', models.CharField(max_length=100)),
                ('Permitted', models.BooleanField(default=False)),
                ('UserName', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accdetails.AccountDetails')),
            ],
        ),
    ]
