# Generated by Django 3.0.7 on 2020-09-10 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accdetails', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Transcation_Id', models.BigIntegerField()),
                ('Money', models.BigIntegerField()),
                ('Type', models.CharField(choices=[('1', 'Deposit'), ('2', 'Withdraw')], max_length=1)),
                ('Username', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accdetails.AccountDetails')),
            ],
        ),
    ]
