# Generated by Django 3.0.7 on 2020-09-10 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accdetails', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location', models.CharField(max_length=50)),
                ('DOB', models.DateField()),
                ('mobile_number', models.IntegerField()),
                ('purpose', models.CharField(max_length=100)),
                ('Amount', models.IntegerField()),
                ('Interest', models.IntegerField()),
                ('collateral', models.CharField(choices=[('1', 'House'), ('2', 'Land'), ('3', 'Others')], max_length=1)),
                ('Approved', models.BooleanField(default=False)),
                ('Recipent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accdetails.AccountDetails')),
            ],
        ),
    ]
