# Generated by Django 3.0.7 on 2020-09-10 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accdetails', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankingSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Balance', models.BigIntegerField()),
                ('Username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accdetails.AccountDetails')),
            ],
        ),
    ]
